[package]
name = "xulin-web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
serde = {version="1.0", features=["derive"]}
actix-cors = "0.6.2"
env_logger = "0.9"
serde_json = "1.0"